### ISSUE TITLE
Don't touch quoted attribute values

### ISSUE THREAD

**Issue by lydell** [ben-eb/postcss-minify-selectors#1]
For example, `[data-selector=" *.class "]` should not be changed in any way.

**Comment by ben-eb** [comment]
This is a problem with the regex which is supposed to handle *qualified* universal selectors (https://github.com/ben-eb/postcss-minify-selectors/blob/master/index.js#L28). Leading/trailing whitespaces are not touched in quoted values. You can see the output with this test case:

```js
{
    message: 'should preserve the universal selector in attribute selectors',
    fixture: 'h1[class=" *.js "] + *.js{color:blue}',
    expected: 'h1[class=" *.js "]+.js{color:blue}'
}
```

```
     ---
       operator: equal
       expected: 'h1[class=" *.js "]+.js{color:blue}'
       actual:   'h1[class=" .js "]+.js{color:blue}'
       at: Test.<anonymous> (/Users/bbriggs/projects/postcss-minify-selectors/test.js:118:11)
     ...
```

I'm not sure if a regex is the right way to go here.

**Comment by lydell** [comment]
It's not just the universal selector and leading/trailing whitespace: Also consecutive/combinator-surrounding whitespace, comments, parentheses messing with `:not()`, 'from' and '100%'.

**Comment by ben-eb** [comment]
Could you please elaborate with some test cases?

**Comment by lydell** [comment]
Something like this:

```js
 {
    message: 'should not change strings',
    fixture: ':not([attr="  h1       a + b /* not a comment */ end of :not ) ?? from 100% "])',
    expected: ':not([attr="  h1       a + b /* not a comment */ end of :not ) ?? from 100% "])'
}
```

**Comment by ben-eb** [comment]
OK, thanks. Will take a look. :smile:

**Comment by lydell** [comment]
Perhaps off-topic, but you should make sure that `5100%` does not become `5to` and that `x-from-tag` does not become `x-0%-tag`. `\b` should be useful here.

**Comment by ben-eb** [comment]
* `x-from-tag` ?
* Are values over `100%` legal in keyframe animations?

**Comment by lydell** [comment]
- `x-from-tag`: custom tag. You may name custom tags anything (alphanumeric I think) as long as it starts with `x-`.
- I don't know. But it's easy to be robust here: `/\b100%\b/` should do the trick.

Ok, these are obviously edge cases, but I nevertheless think they should be fixed.

**Comment by ben-eb** [comment]
Agreed on `/\b100%\b/`. :+1:

**Comment by ben-eb** [comment]
`\b` is not that simple, in JS. I've fixed this, nevertheless.

**Comment by lydell** [comment]
You cheated on the "should not change strings" case by removing the `)`.

**Comment by ben-eb** [comment]
Ah whoops, I had originally changed it because PostCSS was throwing errors on the test case - turns out that it was because the test case did not have a rule block, i.e. `{color:blue}` but I forgot to change it back. Anyway, with that added it now passes that case too. :smile:

**Comment by lydell** [comment]
Hmm, I thought that would fail. What about `[a=":not( *.b,   h1,   h1 )"]`?

**Comment by ben-eb** [comment]
It passes. I wrote a parser that will ignore everything inside both single & double quotes, accounting for escape sequences.

**Comment by lydell** [comment]
Great! Good job. (That might nevertheless be a good test case to add.)

**Comment by ben-eb** [comment]
I'll have a look on next update. :smile:

**Comment by lydell** [comment]
Yet another good test case: `:not( *[href="foo"]  )` -> `:not([href="foo"])`.
